codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...90"
  status:
    patch:
      default:
        target: 30%
    project:
      default:
        target: 85%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/aws_cidr_finder/__init__.py"
